sudo: required
dist: xenial
language: java
jdk:
  - openjdk10

before_install:
    - sudo apt-get update
    - sudo apt-get install --yes m4 libgmp-dev
    - git clone https://github.com/verificatum/verificatum-gmpmee.git; cd verificatum-gmpmee; make -f Makefile.build; ./configure; make; sudo make install; cd -; sudo /sbin/ldconfig
    - git clone https://github.com/verificatum/verificatum-vmgj.git; cd verificatum-vmgj; make -f Makefile.build; ./configure; make; sudo make install; cd -; sudo /sbin/ldconfig
    - git clone https://github.com/verificatum/verificatum-vec.git; cd verificatum-vec; make -f Makefile.build; ./configure; make; sudo make install; cd -; sudo /sbin/ldconfig
    - git clone https://github.com/verificatum/verificatum-vecj.git; cd verificatum-vecj; make -f Makefile.build; ./configure; make; sudo make install; cd -; sudo /sbin/ldconfig
    - git clone https://github.com/verificatum/verificatum-vcr.git; cd verificatum-vcr; make -f Makefile.build; ./configure --enable-vmgj --enable-vecj; make; sudo make install; cd -; sudo /sbin/ldconfig
    - /usr/local/bin/vcr-3.0.3-info jar

script:
    - make -f Makefile.build && ./configure && make && make check
