sudo: required
dist: xenial
language: java

jdk:
  - openjdk11

# Beware that if any Makefile does a make as root, the Java version
# is not necessarily the one specified for the user of this job.

before_install:
    - sudo apt-get update
    - sudo apt-get install --yes m4 libgmp-dev
    - git clone https://github.com/verificatum/verificatum-gmpmee.git && cd verificatum-gmpmee && make -f Makefile.build && ./configure && make && sudo make install && cd - && sudo /sbin/ldconfig
    - git clone https://github.com/verificatum/verificatum-vmgj.git && cd verificatum-vmgj && make -f Makefile.build && ./configure && make && sudo make install && cd - && sudo /sbin/ldconfig
    - git clone https://github.com/verificatum/verificatum-vec.git && cd verificatum-vec && make -f Makefile.build && ./configure && make && sudo make install && cd - && sudo /sbin/ldconfig
    - git clone https://github.com/verificatum/verificatum-vecj.git && cd verificatum-vecj && make -f Makefile.build && ./configure && make && sudo make install && cd - && sudo /sbin/ldconfig
    - git clone https://github.com/verificatum/verificatum-vcr.git && cd verificatum-vcr && make -f Makefile.build && ./configure --enable-vmgj --enable-vecj && make && sudo make install && cd - && sudo /sbin/ldconfig

# This tests that the software works as intended when installed the
# standard way. This is more meaningful then testing within a
# directory.

script:
    - make -f Makefile.build && ./configure && make && sudo make install && make check
